=== ImaneElhirech/Devoir_GL-IHM/XMLForms/figures.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/figures" xmlns:tns="http://www.example.org/figures" elementFormDefault="qualified">

    <element name="figures" type="tns:figures"></element>
    
    <complexType name="figures">
    	<sequence maxOccurs="unbounded">
    		<element name="ligne" type="tns:ligne" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="cercle" type="tns:cercle" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="rectangle" type="tns:rectangle" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="triangle" type="tns:triangle" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="annotation" type="tns:annotation" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>



    <complexType name="ligne">
    	<sequence>
    		<element name="point1" type="tns:point"></element>
    		<element name="point2" type="tns:point"></element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    </complexType>

    <complexType name="cercle">
    	<sequence>
    		<element name="point1" type="tns:point"></element>
    		<element name="point2" type="tns:point"></element>
    		<element name="centre" type="tns:point"></element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="rayon" type="float"></attribute>
    </complexType>

    <complexType name="rectangle">
    	<sequence>
    		<element name="point1" type="tns:point"></element>
    		<element name="point2" type="tns:point"></element>
    		<element name="centre" type="tns:point"></element>
    	</sequence>
    	<attribute name="largeur" type="double"></attribute>
    	<attribute name="longueur" type="double"></attribute>
    	<attribute name="name" type="string"></attribute>
    </complexType>

    <complexType name="triangle">
    	<sequence>
    		<element name="point1" type="tns:point"></element>
    		<element name="point2" type="tns:point"></element>
    		<element name="point3" type="tns:point"></element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    </complexType>

    <complexType name="point">
    	<attribute name="x" type="int"></attribute>
    	<attribute name="y" type="int"></attribute>
    </complexType>

    <complexType name="annotation">
    	<sequence></sequence>
    	<attribute name="composant" type="string"></attribute>
    	<attribute name="relation" type="string"></attribute>
    </complexType>
</schema>

=== ImaneElhirech/Devoir_GL-IHM/XMLForms/FenetreXsd.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<figures xmlns="http://www.example.org/figures" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/figures figures.xsd ">


<figures>
<rectangle largeur="100.0" longueur="80.0" name="rect">
<point1 x="71" y="73"/><point2 x="71" y="73"/>
<centre x="121" y="113"/>
</rectangle>
<cercle name="cer" rayon="50.0">
<point1 x="269" y="106"/>
<point2 x="269" y="106"/>
<centre x="269" y="106"/>
</cercle>
<ligne name="l1">
<point1 x="395" y="73"/>
<point2 x="460" y="173"/>
</ligne>
<ligne name="l2">
<point1 x="465" y="59"/>
<point2 x="547" y="162"/>
</ligne>
<triangle name="tri">
<point1 x="681" y="95"/>
<point2 x="681" y="95"/>
<point3 x="5" y="9"/>
</triangle>
<annotation composant="  composant1 l1  composant2 l2" relation="parallÃ¨les"/>
</figures>
